# CREDENCIAIS DE ACESSO AO SISTEMA DE CONSULTA DO CEMADEN
CEMADEN_URL=''
CEMADEN_EMAIL=''
CEMADEN_PASS=''

# DADOS DE CONEXAO AO BANCO DE DADOS
DB_DATABASE=''
DB_USER=''
DB_PASSWORD=''
DB_HOST=''
DB_PORT=''

# @TODO: Preencher tambem as variaveis do arquivo "public/conect/config.php"